language: python
cache: pip

python:
  - "3.6"

before_install:
  - sh ./scripts/build.sh
  - sudo apt-get install -y golang
  - go get github.com/upyun/upx
  - go version

script:
  - sh ./scripts/deploy.sh

branches:
  only:
    - master