language: python

python:
  - "3.6"

install:
  - pip install mkdocs

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  script: mkdocs build --clean
  on:
    branch: master
