language: python

python:
  - "3.6"

install:
  - pip install mkdocs

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  skip_cleanup: true
  script:
    - mkdocs gh-deploy --clean
  on:
    branch: master
 
#deploy:
#  provider: pages
#  #local-dir: "tmp"
#  target-branch: "gh-pages"
#  github_token: ${GITHUB_TOKEN}
#  on:
#    branch: master




