language: python
cache: pip

python:
  - "3.6"

install:
  - pip install mkdocs # =='0.17.5'
  - pip install mkdocs-material
  - pip install pygments
  - pip install pymdown-extensions
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs -V
  - mkdocs gh-deploy --force --clean

branches:
  only:
    - master