language: python
cache: pip

python:
  - "3.6"

before_install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pygments
  - pip install pymdown-extensions
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

install:
  - sudo echo '165.254.60.149 v0.api.upyun.com' >> /etc/hosts
  - ping v0.api.upyun.com -c 5
  - sudo apt-get install -y golang
  - go get github.com/polym/upx
  - go version

script:
  - mkdocs -V
  # - mkdocs gh-deploy --force --clean
  - mkdocs build --clean
  - upx login "${UPX_SERVICE_NAME}" "${UPX_OPERATOR}" "${UPX_PASSWORD}"
  - upx sync ./site/

branches:
  only:
    - master