language: python

python:
  - "3.6"

install:
  - pip install mkdocs
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  # - git push origin gh-pages --delete
  - mkdocs gh-deploy --help
  - mkdocs gh-deploy -f --clean