language: python

python:
  - "3.6"

install:
  - pip install mkdocs
  
script: mkdocs build --clean

deploy:
  provider: pages
  #local-dir: "site"
  target-branch: "gh-pages"
  github_token: ${GITHUB_TOKEN}
  on:
    branch: master
