language: python
cache: pip

python:
  - "3.6"

before_install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pygments
  - pip install pymdown-extensions
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

install:
  - sudo apt-get install -y golang
  - go get github.com/polym/upx
  - go version

script:
  - mkdocs -V
  - mkdocs gh-deploy --force --clean
  - sudo ~/go/bin/upx login "${UPX-SERVICE-NAME}" "${UPX-OPERATOR}" "${UPX-PASSWORD}"
  - sudo ~/go/bin/upx sync ./site/

branches:
  only:
    - master