language: python

python:
  - "3.6"

install:
  - pip install mkdocs
  - pip install sphinx_rtd_theme
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs gh-deploy --force --clean