language: python

python:
  - "3.6"

install:
  - pip install mkdocs
 
deploy:
  provider: pages
  #local-dir: "tmp"
  target-branch: "gh-pages"
  github_token: ${GITHUB_TOKEN}
  on:
    branch: master

script:
  - mkdocs gh-deploy


