language: python
cache: pip

python:
  - "3.6"

before_install:
  - sh ./scripts/build.sh
  - sudo sh ./scripts/build_upx.sh

script:
  - sh ./scripts/deploy.sh

branches:
  only:
    - master