language: python

python:
  - "3.6"

install:
  - pip install mkdocs

deploy:
  provider: pages
  local-dir: "site"
  target-branch: "gh-pages"
  github_token: ${GITHUB_TOKEN}
  script: mkdocs build --clean
  on:
    branch: master
