site_name: 叶子坑-Docs
site_author: Flc
repo_url: https://github.com/flc1125/docs
theme:
  name: 'material'
  language: 'zh'
  feature:
    tabs: true
  palette:
    primary: red
    accent: red
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      # linenums: true # 显示行号
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  # pymdown-extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css: [static/css/extra.css]
copyright: 'Copyright &copy; <a href="http://flc.io" target="_black">叶子坑</a>'
google_analytics: ['UA-118478085-1', 'auto']
pages:
- 首页: 'index.md'
- PHP:
    - PHP PSR 编码规范:
        - 概述: 'php/psr/index.md'
        - PHP PSR-0 自动加载规范: 'php/psr/psr-0.md'
        - PHP PSR-1 基本代码规范: 'php/psr/psr-1.md'
        - PHP PSR-2 代码风格规范: 'php/psr/psr-2.md'
        - PHP PSR-3 日志接口规范: 'php/psr/psr-3.md'
        - PHP PSR-4 自动载入Autoloader: 'php/psr/psr-4.md'
        - PHP PSR-4 相关示例: 'php/psr/psr-4-examples.md'
        - PHP PSR-7 HTTP消息接口: 'php/psr/psr-7.md'

    - PHPDoc 编码注释规范: 'php/phpdoc/index.md'