site_name: 叶子坑-文档库
site_author: Flc
site_description: 叶子坑文档库，记录相关技术的教程、代码
repo_url: https://github.com/flc1125/docs
site_url: https://docs.flc.io
theme:
  name: 'material'
  language: 'zh'
  favicon: '/favicon.ico'
  feature:
    tabs: true
  palette:
    primary: red
    accent: red
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  # pymdown-extensions
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight:
      # css_class: codehilite # https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - static/css/extra.css
copyright: 'Copyright &copy; 2017-2018 <a href="http://flc.io" target="_black">叶子坑</a>'
google_analytics: ['UA-118478085-1', 'auto']
extra:
  social:
    - type: 'home'
      link: 'http://flc.io'
    - type: 'github'
      link: 'https://github.com/flc1125'
  # disqus: 'flc-docs' # 需翻墙

nav:
- 首页: 'index.md'
- PHP:
    - PHP 各版本特性:
      - PHP 7.2.x: 'php/features/7.2.x.md'
      - PHP 7.1.x: 'php/features/7.1.x.md'
      - PHP 7.0.x: 'php/features/7.0.x.md'
      - PHP 5.6.x: 'php/features/5.6.x.md'
      - PHP 5.5.x: 'php/features/5.5.x.md'
      - PHP 5.4.x: 'php/features/5.4.x.md'
      - PHP 5.3.x: 'php/features/5.3.x.md'
    - PHP PSR 编码规范:
      - 概述: 'php/psr/index.md'
      - PHP PSR-0 自动加载规范: 'php/psr/psr-0.md'
      - PHP PSR-1 基本代码规范: 'php/psr/psr-1.md'
      - PHP PSR-2 代码风格规范: 'php/psr/psr-2.md'
      - PHP PSR-3 日志接口规范: 'php/psr/psr-3.md'
      - PHP PSR-4 自动载入Autoloader: 'php/psr/psr-4.md'
      - PHP PSR-4 相关示例: 'php/psr/psr-4-examples.md'
      - PHP PSR-7 HTTP消息接口: 'php/psr/psr-7.md'
    - PHPDoc 编码注释规范: 'php/phpdoc/index.md'
    - PHP Coding Standards Fixer: 'php/php-cs-fixer/index.md'
    - PHP 设计模式全集:
      - 概述: 'php/php-design-patterns/index.md'
      - 创建型:
        - 抽象工厂模式（Abstract Factory）: 'php/php-design-patterns/AbstractFactory.md'
        - 建造者模式（Builder）: 'php/php-design-patterns/Builder.md'
        - 工厂方法模式（Factory Method）: 'php/php-design-patterns/FactoryMethod.md'
        - 多例模式（Multiton）: 'php/php-design-patterns/Multiton.md'
        - 对象池模式（Pool）: 'php/php-design-patterns/Pool.md'
        - 原型模式（Prototype）: 'php/php-design-patterns/Prototype.md'
        - 简单工厂模式（Simple Factory）: 'php/php-design-patterns/SimpleFactory.md'
        - 单例模式（Singleton）: 'php/php-design-patterns/Singleton.md'
        - 静态工厂模式（Static Factory）: 'php/php-design-patterns/StaticFactory.md'
      - 结构型:
        - 适配器模式（Adapter）: 'php/php-design-patterns/Adapter.md'
        - 桥梁模式（Bridge）: 'php/php-design-patterns/Bridge.md'
        - 组合模式（Composite）: 'php/php-design-patterns/Composite.md'
        - 数据映射模式（Data Mapper）: 'php/php-design-patterns/DataMapper.md'
        - 装饰模式（Decorator）: 'php/php-design-patterns/Decorator.md'
        - 依赖注入模式（Dependency Injection）: 'php/php-design-patterns/DependencyInjection.md'
        - 门面模式（Facade）: 'php/php-design-patterns/Facade.md'
        - 流接口模式（Fluent Interface）: 'php/php-design-patterns/FluentInterface.md'
        - 享元模式（Flyweight）: 'php/php-design-patterns/Flyweight.md'
        - 代理模式（Proxy）: 'php/php-design-patterns/Proxy.md'
        - 注册模式（Registry）: 'php/php-design-patterns/Registry.md'
      - 行为型:
        - 责任链模式（Chain Of Responsibilities）: 'php/php-design-patterns/ChainOfResponsibilities.md'
        - 命令行模式（Command）: 'php/php-design-patterns/Command.md'
        - 迭代器模式（Iterator）: 'php/php-design-patterns/Iterator.md'
        - 中介者模式（Mediator）: 'php/php-design-patterns/Mediator.md'
        - 备忘录模式（Memento）: 'php/php-design-patterns/Memento.md'
        - 空对象模式（Null Object）: 'php/php-design-patterns/NullObject.md'
        - 观察者模式（Observer）: 'php/php-design-patterns/Observer.md'
        - 规格模式（Specification）: 'php/php-design-patterns/Specification.md'
        - 状态模式（State）: 'php/php-design-patterns/State.md'
        - 策略模式（Strategy）: 'php/php-design-patterns/Strategy.md'
        - 模板方法模式（Template Method）: 'php/php-design-patterns/TemplateMethod.md'
        - 访问者模式（Visitor）: 'php/php-design-patterns/Visitor.md'
      - 更多类型:
        - 委托模式（Delegation）: 'php/php-design-patterns/Delegation.md'
        - 服务定位器模式（Service Locator）: 'php/php-design-patterns/ServiceLocator.md'
        - 资源库模式（Repository）: 'php/php-design-patterns/Repository.md'
        - 实体属性值模式（EAV 模式）: 'php/php-design-patterns/EAV.md'
      - 附录:
        - 反面模式（Anti-pattern）: 'php/php-design-patterns/Anti-pattern.md'
        - PHP 设计模式阅读清单: 'php/php-design-patterns/design-pattern-reading.md'
- Elasticsearch:
  - Elasticsearch 简易教程:
    - Elasticsearch 入门: 'elasticsearch/simple/introduction.md'
    - Elasticsearch 入门(二): 'elasticsearch/simple/introduction2.md'
    - PHP DSL 查修构造器扩展: 'elasticsearch/simple/builder.md'
  - Laravel-Elasticsearch 扩展文档:
      - 安装与配置: 'elasticsearch/laravel-elasticsearch/introduction.md'
      - 查询构造器: 'elasticsearch/laravel-elasticsearch/builder.md'
  - Elasticsearch-PHP:
    - 概述: 'elasticsearch/elasticsearch-php/overview.md'
    - 快速开始: 'elasticsearch/elasticsearch-php/quickstart.md'
    - 安装: 'elasticsearch/elasticsearch-php/installation.md'
    - 配置: 'elasticsearch/elasticsearch-php/configuration.md'
    - 按请求配置: 'elasticsearch/elasticsearch-php/per_request_configuration.md'
    - Future 模式: 'elasticsearch/elasticsearch-php/future_mode.md'
    - PHP 处理 JSON 数组或对象: 'elasticsearch/elasticsearch-php/php_json_objects.md'
    - 索引管理: 'elasticsearch/elasticsearch-php/index_management_operations.md'
    - 索引文档: 'elasticsearch/elasticsearch-php/indexing_documents.md'
    - 获取文档: 'elasticsearch/elasticsearch-php/getting_documents.md'
    - 更新文档: 'elasticsearch/elasticsearch-php/updating_documents.md'
    - 删除文档: 'elasticsearch/elasticsearch-php/deleting_documents.md'
    - 搜索操作: 'elasticsearch/elasticsearch-php/search_operations.md'
    - 命名空间: 'elasticsearch/elasticsearch-php/namespaces.md'
    - 安全: 'elasticsearch/elasticsearch-php/security.md'
    - 连接池: 'elasticsearch/elasticsearch-php/connection_pool.md'
    - 选择器: 'elasticsearch/elasticsearch-php/selectors.md'
    - 序列化器: 'elasticsearch/elasticsearch-php/serializers.md'
    - PHP 版本需求: 'elasticsearch/elasticsearch-php/php_version_requirement.md'
    - 社区 DSLs: 'elasticsearch/elasticsearch-php/community_dsls.md'
  # - Elasticsearch 全/增量同步:
  #   - 概述: 'elasticsearch/elasticsearch-sync/index.md'
- DevOps:
  - CDN 科普: 'devops/cdn/index.md'
  - Docker:
    - 概述: 'devops/docker/index.md'
    - Dockerfile:
      - PHP: 'devops/docker/dockerfile/php.md'
  - Redis: 'devops/redis/index.md'
- Awesome:
  - PHP: 'awesome/php.md'
# - 百家“争鸣”:
#   - 推荐博客: 'hundred/blog.md'
#   - 开源工具: 'hundred/open-source.md'
#   - 知识点: 'hundred/knowledge.md'
- 更多:
  - Github + Travis + Mkdocs 搭建文档库: 'more/github-travis-mkdocs-document/index.md'
  - Git 常用命令: 'more/git/index.md'
  - 中文技术文档的写作规范:
    - 概述: 'more/document-style-guide/index.md'
    - 标题: 'more/document-style-guide/title.md'
    - 文本: 'more/document-style-guide/text.md'
    - 段落: 'more/document-style-guide/paragraph.md'
    - 数值: 'more/document-style-guide/number.md'
    - 标点符号: 'more/document-style-guide/marks.md'
    - 文档体系: 'more/document-style-guide/structure.md'
    - 参考链接: 'more/document-style-guide/reference.md'