name: Deploy to UPYUN
on: push
#   push:
#     branchs: [master]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        run: python -V

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          mkdocs -V

      - name: Golang
        uses: actions/setup-go@v2
        run: go version

      - name: Install UPX
        run: |
          go get -u github.com/upyun/upx@v0.3.1
          upx -v

      - name: Build
        run: |
          mkdocs build --clean