name: Deploy Site
on:
  push:
    branchs: [master]

env:
  GO111MODULE: "on"
  UPX_SERVICE_NAME: ${{ secrets.UPX_SERVICE_NAME }}
  UPX_OPERATOR: ${{ secrets.UPX_OPERATOR }}
  UPX_PASSWORD: ${{ secrets.UPX_PASSWORD }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          python -V
          pip -V

      # - name: Install Python
      #   uses: actions/checkout@v3
      #   with:
      #     python-version: "3.9"
      #     cache: pip
      # - run: |
      #     python -V
      #     pip -V

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          mkdocs -V

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - run: go version

      - name: Install Upx
        run: |
          go get -u github.com/upyun/upx@v0.3.6

      - name: Login Upx
        run: |
          ${HOME}/go/bin/upx login "${{ env.UPX_SERVICE_NAME }}" "${{ env.UPX_OPERATOR }}" "${{ env.UPX_PASSWORD }}"

      - name: Build
        run: |
          mkdocs build --clean

      - name: Deploy
        run: |
          ${HOME}/go/bin/upx sync ./site/
