name: Deploy to UPYUN
on: push
#   push:
#     branchs: [master]

env:
  UPX_SERVICE_NAME: ${{ secrets.UPX_SERVICE_NAME }}
  UPX_OPERATOR: ${{ secrets.UPX_OPERATOR }}
  UPX_PASSWORD: ${{ secrets.UPX_PASSWORD }}


jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2


      - name: Install dependencies
        run: |
          python -V
          pip install -r requirements.txt
          mkdocs -V

      - name: Golang
        uses: actions/setup-go@v2

      - name: Install Upx
        run: |
          go version
          GO111MODULE=on go get -u github.com/upyun/upx@v0.3.2

      - name: Login Upx
        run: |
          upx login "${{ env.UPX_SERVICE_NAME }}" "${{ env.UPX_OPERATOR }}" "${{ env.UPX_PASSWORD }}"

      - name: Build
        run: |
          mkdocs build --clean

      - name: Deploy
        run: |
          upx sync ./site/
